// HERO
export const REQUEST_HEROES = 'REQUEST_HEROES';
export const RECEIVE_HEROES = 'RECEIVE_HEROES';
export const SET_HEROES_LIMIT = 'SET_HEROES_LIMIT';
export const SET_HERO_TEAM_TITLE = 'SET_HERO_TEAM_TITLE';
export const ADD_HERO_TO_TEAM = 'ADD_HERO_TO_TEAM';
export const REMOVE_HERO_FROM_TEAM = 'REMOVE_HERO_FROM_TEAM';
export const NEW_HERO = 'NEW_HERO';

// NAVIGATION
export const SET_TITLE = 'SET_TITLE';
